### PR TITLE
chore(Bevy): Update to bevy 0.13 

### LINKED ISSUE #132: Update to Bevy 0.13
* [x] update all crates & examples to Bevy 0.13

### LINKED ISSUE #137: Custom `assets` directory is ignored
Didn't do a hard dive into this one, but at least the registry plugin uses a hardcoded path to `"assets/..."`. We should instead read the assets path from the `AssetPlugin`. For reference, this is how I did it for Yarn Spinner: https://github.com/YarnSpinnerTool/YarnSpinner-Rust/blob/v0.2.0/crates/bevy_plugin/src/plugin.rs#L245-L256

### LINKED ISSUE #144: Add a `GltfProcessed` marker to objects
As we discussed in Discord, we currently iterate over all Gltf models on every frame. If we add a `GltfProcessed` marker to the objects after reading their `GltfExtras`, we can constrain the query with a `Without<GltfProcessed>`, which is an archetype and thus makes the query not need to loop over everything.

### LINKED ISSUE #155: Add `AmbientLightSettings`, `ShadowmapSettings`, and `lighting_replace_proxies` to crate

### LINKED ISSUE #157: Export lights' shadows being enabled or not in Blender

### PR DESCRIPTION
**Pull request by kaosat-dev**
* chore(crates): updated crates to Bevy 0.13
   * updated deps
   * updated / changed code where relevant
   * updated README files
   * bumped version numbers for upcoming release
   * updated rust-toolchain
   * updated assets where relevant
   * closes #132 
* feat(bevy_gltf_components): 
  * added GltfProcessed flag component to improve performance of iteration over added<gltfExtras>
  * closes #144 
  * light & shadow processing is now integrated,  to match  lights coming from Blender: you can now control whether 
  lights cast shadows, the cascade resolution , background color etc  from Blender
   * closes #155 

* feat(bevy_registry_export): added boilerplate to make registry path relative to assets folder 
  * closes #137 
* feat(tools): added boilerplate for internal tools
   * clean zip file generator for blender add-on releases
   * example gltf file generator
* feat(lighting): added components, exporter support & testing for blender-configurable shadows
   * added BlenderLightShadows component to bevy_gltf_components
   * added writing shadow information to gltf_auto_export
   * updated tests
   * closes #157 

Co-authored-by: Jan Hohenheim <jan@hohenheim.ch>

### CODE REVIEW

**Comment by janhohenheim** [comment]
FYI, I'm testing this branch on Foxtrot and I got this crash:
image

After restarting the game everything works fine.

**Comment by kaosat-dev** [comment]
> FYI, I'm testing this branch on Foxtrot and I got this crash: image
> 
> After restarting the game everything works fine.

Ouch ! I should call you the bug-finder;)
Hmm is there any backtrace to find more information about where the issue comes from ?

**Comment by janhohenheim** [comment]
The fact that it only came up once tells me its probably a scheduling error

**Comment by janhohenheim** [comment]
The bug-finder mayyyy have struck again: https://github.com/kaosat-dev/Blender_bevy_components_workflow/pull/143

**Pull request merged**
