### PR TITLE
Add lint CI

### PR DESCRIPTION
**Pull request by GitGhillie**
Copied from https://github.com/NiklasEi/bevy_game_template

Checks for fmt and clippy on each PR so you can see whether someone's PR is up to standards.

PS: Congrats on 100 PRs/issues! Sorry to steal the spotlight with a boring CI PR >:)

### CODE REVIEW

**Comment by GitGhillie** [comment]
Seems like there is an issue with this, turning it into a draft for the time being

**Comment by GitGhillie** [comment]
Alright it works now, you can preview the output on my branch. It is failing on some clippy warnings but that's work for another PR in my opinion.

**Comment by kaosat-dev** [comment]
> Copied from https://github.com/NiklasEi/bevy_game_template
> 
> Checks for fmt and clippy on each PR so you can see whether someone's PR is up to standards.
> 
> PS: Congrats on 100 PRs/issues! Sorry to steal the spotlight with a boring CI PR >:)

Thanks a lot for this :) ! It has been bothering me since the start not to have working tests & CI , so this is much appreciated :+1: 

And I do not mind at all, CI is essential ! ;)

**Comment by GitGhillie** [comment]
Only need to do the thing where you allow complex types and arguments (can also be in a different PR). Checking now what the best way is to do that

**Comment by kaosat-dev** [comment]
> Alright it works now, you can preview the output on my branch. It is failing on some clippy warnings but that's work for another PR in my opinion.

I'll take a look in details later today or tomorrow, I tried using clippy a few month back and it gave me headaches trying to resolve things, but I am confidant my improved "Rust brain" will manage this time :D

**Comment by GitGhillie** [comment]
Bevy has this in the main Cargo.toml:
```
[workspace.lints.clippy]
type_complexity = "allow"
doc_markdown = "warn"
manual_let_else = "warn"
undocumented_unsafe_blocks = "warn"
redundant_else = "warn"
match_same_arms = "warn"
semicolon_if_nothing_returned = "warn"
map_flatten = "warn"

[lints]
workspace = true
```

**Comment by GitGhillie** [comment]
> I'll take a look in details later today or tomorrow, I tried using clippy a few month back and it gave me headaches trying to resolve things, but I am confidant my improved "Rust brain" will manage this time :D

Let me know if you get stuck!

**Comment by GitGhillie** [comment]
> Bevy has this in the main Cargo.toml:
> 
> ```
> [workspace.lints.clippy]
> type_complexity = "allow"
> doc_markdown = "warn"
> manual_let_else = "warn"
> undocumented_unsafe_blocks = "warn"
> redundant_else = "warn"
> match_same_arms = "warn"
> semicolon_if_nothing_returned = "warn"
> map_flatten = "warn"
> 
> [lints]
> workspace = true
> ```

I checked the lints out, they seem reasonable. I only removed map_flatten as it seems to be `warn` by default.
Finally, I had to update the rust version used to be able to make use of the "workspace-wide lints in the Cargo.toml's" feature.
Everything should be good now.

**Comment by kaosat-dev** [comment]
This looks very good, much appreciated ! :)
I checked out the various clippy lint settings etc and it all seems good to me !
And sorry it took me so long ;)
Very happy to finally have CI & linting !

**Comment by GitGhillie** [comment]
Awesome!

**Pull request merged**
