### PR TITLE
feat(gltf_auto_export):

### LINKED ISSUE #139: There's a lot of warn spam about animation interpolation steps
The animation example and my own code produce the warning "Animation interpolation Step is not supported, will use linear" even though all interpolation steps are linear. AFAIK there are two scenarios where this can happen:
- Animations are exported with optimizations. Does the `bevy_components` do this? If so, it shouldn't.
- An invalid or no animation at all is registered in an animation clip. This can happen if something went wrong during the GLTF export or simply when the first NLA track is empty.

For reference, this is the output of the animations example:
image

### LINKED ISSUE #141: Add filtering out of specific custom properties on export
There are a number of internal, Blender specific custom_properties that we do NOT want to export as part of the gltf files,
these should be filtered out before export
- [x] components_meta (for **Bevy_components**)
- [x] disable components (also related to the above)

As there is no direct way to do this in Blender, the workaround will likely need to be
* for each object to export
  * check for unwanted custom properties
  * if present, do a back up (object name + custom prop name + value)
  * export
  * re-apply custom property

### LINKED ISSUE #142: Setting gltf parameters breaks export
Setting parameters such as the gltf type (gltf vs glb) breaks the auto_export process

### LINKED ISSUE #146: Add tests for gltf_auto_export
Now that we have some (local, not yet CI) tests running for ```bevy_components``` it would be nice to have tests for gltf_auto_export as well

### PR DESCRIPTION
**Pull request by kaosat-dev**
* added filtering out of invalid components/ custom properties:
  * includes filtering out of invalid / disabled components as defined in bevy_components, components_meta etc
 * completely changed handling of "unique" (non blueprint) objects by copying them instead of moving/renaming them & manipulating their custom properties : much cleaner, much simpler !
 * disabled default gltf export of optimised animations
 * added tests !
 * closes #139 
 * closes #141 
 * closes #142 
 * closes #146

### CODE REVIEW

**Comment by janhohenheim** [comment]
This also makes #138 obsolete, right?

**Comment by janhohenheim** [comment]
Using the newest `gltf_auto_export` just caused my fox model to vanish.
See this branch: https://github.com/janhohenheim/foxtrot/pull/297

**Comment by kaosat-dev** [comment]
> Using the newest `gltf_auto_export` you just released caused my fox model to vanish. See this branch: [janhohenheim/foxtrot#297](https://github.com/janhohenheim/foxtrot/pull/297) image Using the inspector, I can see that no Handle lands on the player.
> 
> Note the `main` branch uses the `gltf_auto_export` you linked in #139, which does not have this problem.
> 
> Could you open the .blend file in the assets/scenes folder and check whether you can reproduce this? It seems a bit strange to me, like the export shouldn't really be able to do this, so it might just be something weird on my end.

Tested it out, and its confirmed, found the source of the issue: dammit, one of Blender's weird internal logic hits again:
it seems that ```original_object.copy()``` does in fact NOT make a complete copy of the original object  , sigh...
Fixing this asap ! And adding it to the tests to avoid regression

**Comment by janhohenheim** [comment]
That was quick, good job! :)

**Pull request merged**
